language: node_js
node_js:
  - 10
cache:
  npm: true
  directories:
    - ~/.npm
    - ~/.cache
install:
  - npm install codecov --save-dev
  - npm ci
script:
  - $(npm bin)/cypress run --record
after_success:
  - ./node_modules/.bin/codecov --token=:token
